---
# tasks file for enqack.locale

- name: Gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Check environment
  assert:
    that:
      - locale_package_state is defined
      - locale_package_state == "present" or
        locale_package_state == "latest" or
        locale_package_state == "absent"
      - locale_lang is defined

- name: Install requirements
  package:
    name: "{{ locale_requirements }}"
    state: "{{ locale_package_state }}"
  when:
    - ansible_distribution_release != 'trusty'

- name: Generate locales
  command: locale-gen {{ item }}
  with_items: "{{ locale_locale_gen }}"

- name: Configure locale.conf
  template:
    src: locale.conf.j2
    dest: "{{ locale_configuration_file }}"

- name: Run localectl set-locale
  command: localectl set-locale LANG={{ locale_lang }}
  when:
    - ansible_virtualization_type != "docker" or locale_ignore_docker
    - ansible_os_family != "Debian"

- name: Configure il8n
  lineinfile:
    path: /etc/sysconfig/i18n
    regexp: '^LANG='
    line: 'LANG="{{ locale_lang }}"'
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == 6
